export const FETCH_ABOUT = "FETCH_ABOUT";
export const FETCH_NOW_PLAYING = "FETCH_NOW_PLAYING";
export const FETCH_COMMITS = "FETCH_COMMITS";
export const FETCH_PRODUCTIVITY = "FETCH_PRODUCTIVITY";
export const FETCH_AVAILABILITY = "FETCH_AVAILABILITY";
export const FETCH_REGION = "FETCH_REGION";
