export const ABOUT_EMAIL = "ABOUT_EMAIL";
export const ABOUT_EXCLUDING_CONTACT = "ABOUT_EXCLUDING_CONTACT";

export const NOW_PLAYING = "NOW_PLAYING";
export const NOW_PLAYING_TRACK = "NOW_PLAYING_TRACK";
export const NOW_PLAYING_PROGRESS = "NOW_PLAYING_PROGRESS";
