export const ABOUT_SUCCESS = "ABOUT_SUCCESS";
export const ABOUT_LOADING = "ABOUT_LOADING";
export const ABOUT_FAILURE = "ABOUT_FAILURE";

export const NOW_PLAYING_SUCCESS = "NOW_PLAYING_SUCCESS";
export const NOW_PLAYING_LOADING = "NOW_PLAYING_LOADING";
export const NOW_PLAYING_FAILURE = "NOW_PLAYING_FAILURE";
export const NOW_PLAYING_PROGRESS = "NOW_PLAYING_PROGRESS";

export const PRODUCTIVITY_SUCCESS = "PRODUCTIVITY_SUCCESS";
export const PRODUCTIVITY_LOADING = "PRODUCTIVITY_LOADING";
export const PRODUCTIVITY_FAILURE = "PRODUCTIVITY_FAILURE";

export const COMMITS_SUCCESS = "COMMITS_SUCCESS";
export const COMMITS_LOADING = "COMMITS_LOADING";
export const COMMITS_FAILURE = "COMMITS_FAILURE";

export const AVAILABILITY_SUCCESS = "AVAILABILITY_SUCCESS";
export const AVAILABILITY_LOADING = "AVAILABILITY_LOADING";
export const AVAILABILITY_FAILURE = "AVAILABILITY_FAILURE";

export const REGION_SUCCESS = "REGION_SUCCESS";
export const REGION_LOADING = "REGION_LOADING";
export const REGION_FAILURE = "REGION_FAILURE";
